# Generated by Django 5.1.7 on 2025-05-01 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField()),
                ('nome_aluno', models.CharField(max_length=100)),
                ('matriculado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_emprestimo', models.BooleanField(default=False)),
                ('data_retirada', models.DateTimeField(default=datetime.datetime.now)),
                ('data_devolucao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=400)),
                ('genero', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=100)),
                ('capa', models.ImageField(blank=True, upload_to='capas/%Y/%m/%d/')),
                ('aparecer', models.BooleanField(default=False)),
            ],
        ),
    ]
