# Generated by Django 5.1.7 on 2025-05-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_emprestimo_id_livro_emprestimo_ra_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra_aluno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status_emprestimo',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Atrasado', 'Atrasado')], default='Em andamento', max_length=20),
        ),
    ]
