# Generated by Django 5.1.7 on 2025-05-03 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_livro_quantidade_alter_aluno_ra_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status_emprestimo',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
