# Generated by Django 5.1.7 on 2025-05-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_emprestimo_devolvido_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
