# Generated by Django 5.1.7 on 2025-05-04 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ra_aluno',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='ra_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='galeria.aluno'),
        ),
    ]
