# Generated by Django 5.1.7 on 2025-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_aluno_ra_aluno_alter_emprestimo_ra_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
