# Generated by Django 5.1.7 on 2025-05-05 17:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_retirada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id_livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='ra_aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='galeria.aluno'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status_emprestimo',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
