# Generated by Django 5.1.7 on 2025-05-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
